In [1]:
# Importing packages
import numpy as np
from pychange.costs import L1Cost, L2Cost, NormalMeanCost, NormalVarCost, NormalMeanVarCost, PoissonMeanVarCost, ExponentialMeanVarCost, GammaMeanVarCost, NonParametricCost
from pychange.segment import amoc_segment, pelt_segment, binary_segment
from pychange.online import ConstantHazard, StudentTProb, OnlineCP
from pychange.r import ROfflineChangepoint, ROCP
import ruptures as rpt
%load_ext line_profiler

In [2]:
# Creating Normal synthetic data
size = 10000
sm_size = 100
k = 10
min_len = 10
max_cp = 40
pen = 100.0
test_series = np.hstack([np.random.normal(0, 1, (size,)),
                         np.random.normal(6, 1, (size,)),
                         np.random.normal(0, 2, (size,)),
                         np.random.normal(-4, 1, (size,)),
                         np.random.normal(3, 1, (size,)),
                         ] * 8)

sm_test_series = np.hstack([np.random.normal(0, 1, (sm_size,)),
                         np.random.normal(6, 1, (sm_size,)),
                         np.random.normal(0, 2, (sm_size,)),
                         np.random.normal(-4, 1, (sm_size,)),
                         np.random.normal(3, 1, (sm_size,)),
                         ])

p_test_series = np.hstack([np.random.poisson(2, (size,)),
                         np.random.poisson(6, (size,)),
                         np.random.poisson(10, (size,)),
                         np.random.poisson(4, (size,)),
                         np.random.poisson(3, (size,)),
                         ] * 8)

g_test_series = p_test_series + 1

# AMOC

## Normal Mean

In [23]:
# Normal mean
amoc_segment(NormalMeanCost().fit(test_series), min_len, pen)

20000

In [24]:
ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='AMOC', minseglen=min_len).fit(test_series).predict()

array([20000.])

In [25]:
# Pychange Timing
%timeit amoc_segment(NormalMeanCost().fit(test_series), min_len, pen)

10.1 ms ± 215 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [26]:
# R timing
%timeit ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Normal", minseglen=min_len).fit(test_series).predict()

32 ms ± 1.87 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Normal Var

In [27]:
# Normal mean
amoc_segment(NormalVarCost().fit(test_series), min_len, pen)

10000

In [28]:
ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='AMOC', minseglen=min_len).fit(test_series).predict()

array([10000.])

In [29]:
# Pychange Timing
%timeit amoc_segment(NormalVarCost().fit(test_series), min_len, pen)

22.9 ms ± 132 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
# R timing
%timeit ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Normal", minseglen=min_len).fit(test_series).predict()

48.4 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Normal Mean+Var

In [31]:
# Normal mean
amoc_segment(NormalMeanVarCost().fit(test_series), min_len, pen)

390000

In [32]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', minseglen=min_len).fit(test_series).predict()

array([390000.])

In [33]:
# Pychange Timing
%timeit amoc_segment(NormalMeanVarCost().fit(test_series), min_len, pen)

15.6 ms ± 32 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [34]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Normal", minseglen=min_len).fit(test_series).predict()

64.7 ms ± 2.37 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Poisson Mean+Var

In [35]:
# Normal mean
amoc_segment(PoissonMeanVarCost().fit(p_test_series), min_len, pen)

10000

In [36]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Poisson", minseglen=min_len).fit(p_test_series).predict()

array([10000.])

In [37]:
# Pychange Timing
%timeit amoc_segment(PoissonMeanVarCost().fit(p_test_series), min_len, pen)

12 ms ± 24.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [38]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Poisson", minseglen=min_len).fit(p_test_series).predict()

262 ms ± 6.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Exponential

In [3]:
amoc_segment(ExponentialMeanVarCost().fit(p_test_series), min_len, pen)

10000

In [4]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Exponential", minseglen=min_len).fit(p_test_series).predict()

array([10000.])

In [5]:
%timeit amoc_segment(ExponentialMeanVarCost().fit(p_test_series), min_len, pen)

11.5 ms ± 75.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Exponential", minseglen=min_len).fit(p_test_series).predict()

254 ms ± 6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Gamma

In [3]:
amoc_segment(GammaMeanVarCost().fit(g_test_series), min_len, pen)

10000

In [4]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Gamma", minseglen=min_len).fit(g_test_series).predict()

array([10000.])

In [5]:
%timeit amoc_segment(GammaMeanVarCost().fit(g_test_series), min_len, pen)

11.4 ms ± 44.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Gamma", minseglen=min_len).fit(g_test_series).predict()

246 ms ± 8.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Nonparametric

In [39]:
# Normal mean
amoc_segment(NonParametricCost(k).fit(test_series), min_len, pen)

20000

In [40]:
# Pychange Timing
%timeit amoc_segment(NonParametricCost(k).fit(test_series), min_len, pen)

210 ms ± 1.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Pelt

## L1

In [41]:
# L1 cost
pelt_segment(L1Cost().fit(sm_test_series), min_len, max_cp, pen, 1)

array([100, 200, 300, 400], dtype=int64)

In [42]:
rpt.Pelt(model='l1', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

[100, 200, 300, 400, 500]

In [43]:
%timeit pelt_segment(L1Cost().fit(sm_test_series), min_len, max_cp, pen, 1)

37.5 ms ± 36.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [44]:
%timeit rpt.Pelt(model='l1', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

2.22 s ± 2.18 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## L2

In [45]:
# L1 cost
pelt_segment(L2Cost().fit(sm_test_series), min_len, max_cp, pen, 1)

array([100, 200, 300, 400], dtype=int64)

In [46]:
rpt.Pelt(model='l2', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

[100, 200, 300, 400, 500]

In [47]:
%timeit pelt_segment(L2Cost().fit(sm_test_series), min_len, max_cp, pen, 1)

1.8 ms ± 579 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [48]:
%timeit rpt.Pelt(model='l2', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

700 ms ± 1.24 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Normal Mean

In [49]:
# Normal mean
pelt_segment(NormalMeanCost().fit(test_series), min_len, max_cp, pen, 1)

array([ 10000,  20000,  29999,  40000,  50000,  60000,  70000,  79999,
        90000, 100000, 110000, 120000, 129999, 140000, 150000, 160000,
       170000, 179999, 190000, 200000, 210000, 220000, 229999, 240000,
       250000, 260000, 270000, 279999, 290000, 300000, 310000, 320000,
       329999, 340000, 350000, 360000, 370000, 379999, 390000],
      dtype=int64)

In [50]:
ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

array([ 10000,  20000,  29999,  40000,  50000,  60000,  70000,  79999,
        90000, 100000, 110000, 120000, 129999, 140000, 150000, 160000,
       170000, 179999, 190000, 200000, 210000, 220000, 229999, 240000,
       250000, 260000, 270000, 279999, 290000, 300000, 310000, 320000,
       329999, 340000, 350000, 360000, 370000, 379999, 390000],
      dtype=int32)

In [51]:
# Pychange Timing
%timeit pelt_segment(NormalMeanCost().fit(test_series), min_len, max_cp, pen, 1)

30.2 s ± 205 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [52]:
# R timing
%timeit ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

Exception ignored from cffi callback <function _callback at 0x0000025F6F501DC0>:
Traceback (most recent call last):
  File "C:\Users\15072\anaconda3\envs\pychange\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 313, in _callback
    try:
KeyboardInterrupt: 


8.46 s ± 50 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Normal Var

In [53]:
pelt_segment(NormalVarCost().fit(test_series), min_len, max_cp, pen, 1)

array([   671,    707,  10000,  20001,  29999,  40000,  50013,  50671,
        50707,  60000,  70001,  79999,  90000, 100013, 100671, 100707,
       110000, 120001, 129999, 140000, 150013, 150671, 150707, 160000,
       170001, 179999, 190000, 200013, 200671, 200707, 210000, 220001,
       229999, 240000, 250013, 250671, 250707, 260000, 270001, 279999,
       290000, 300013, 300671, 300707, 310000, 320001, 329999, 340000,
       350013, 350671, 350707, 360000, 370001, 379999, 390000],
      dtype=int64)

In [54]:
ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

array([ 10000,  20001,  29999,  40000,  50007,  60000,  70001,  79999,
        90000, 100007, 110000, 120001, 129999, 140000, 150007, 160000,
       170001, 179999, 190000, 200007, 210000, 220001, 229999, 240000,
       250007, 260000, 270001, 279999, 290000, 300007, 310000, 320001,
       329999, 340000, 350007, 360000, 370001, 379999, 390000],
      dtype=int32)

In [55]:
# Pychange Timing
%timeit pelt_segment(NormalVarCost().fit(test_series), min_len, max_cp, pen, 1)

49.5 s ± 427 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
# R timing
%timeit ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

1min 13s ± 166 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Normal Mean+Var

In [57]:
pelt_segment(NormalMeanVarCost().fit(test_series), min_len, max_cp, pen, 1)

array([ 10000,  20000,  29999,  40000,  50000,  60000,  70000,  79999,
        90000, 100000, 110000, 120000, 129999, 140000, 150000, 160000,
       170000, 179999, 190000, 200000, 210000, 220000, 229999, 240000,
       250000, 260000, 270000, 279999, 290000, 300000, 310000, 320000,
       329999, 340000, 350000, 360000, 370000, 379999, 390000],
      dtype=int64)

In [58]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

array([ 10000,  20000,  29999,  40000,  50000,  60000,  70000,  79999,
        90000, 100000, 110000, 120000, 129999, 140000, 150000, 160000,
       170000, 179999, 190000, 200000, 210000, 220000, 229999, 240000,
       250000, 260000, 270000, 279999, 290000, 300000, 310000, 320000,
       329999, 340000, 350000, 360000, 370000, 379999, 390000],
      dtype=int32)

In [59]:
# Pychange Timing
%timeit pelt_segment(NormalMeanVarCost().fit(test_series), min_len, max_cp, pen, 1)

41.6 s ± 140 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [60]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

1min 44s ± 299 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Poisson Mean+Var

In [61]:
pelt_segment(PoissonMeanVarCost().fit(p_test_series), min_len, max_cp, pen, 1)

array([ 10000,  19998,  30000,  39998,  50000,  60000,  69998,  80000,
        89998, 100000, 110000, 119998, 130000, 139998, 150000, 160000,
       169998, 180000, 189998, 200000, 210000, 219998, 230000, 239998,
       250000, 260000, 269998, 280000, 289998, 300000, 310000, 319998,
       330000, 339998, 350000, 360000, 369998, 380000, 389998],
      dtype=int64)

In [62]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Poisson").fit(p_test_series).predict()

array([ 10000,  19998,  30000,  39998,  50000,  60000,  69998,  80000,
        89998, 100000, 110000, 119998, 130000, 139998, 150000, 160000,
       169998, 180000, 189998, 200000, 210000, 219998, 230000, 239998,
       250000, 260000, 269998, 280000, 289998, 300000, 310000, 319998,
       330000, 339998, 350000, 360000, 369998, 380000, 389998],
      dtype=int32)

In [ ]:
# Pychange Timing
%timeit pelt_segment(PoissonMeanVarCost().fit(p_test_series), min_len, max_cp, pen, 1)

In [ ]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Poisson").fit(p_test_series).predict()

## Exponential Mean+Var

In [7]:
pelt_segment(ExponentialMeanVarCost().fit(p_test_series), min_len, max_cp, pen, 1)

array([ 10000,  19998,  30000,  39997,  50013,  60000,  69998,  80000,
        89997, 100013, 110000, 119998, 130000, 139997, 150013, 160000,
       169998, 180000, 189997, 200013, 210000, 219998, 230000, 239997,
       250013, 260000, 269998, 280000, 289997, 300013, 310000, 319998,
       330000, 339997, 350013, 360000, 369998, 380000, 389997],
      dtype=int64)

In [ ]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Exponential").fit(p_test_series).predict()

Exception ignored from cffi callback <function _callback at 0x0000013DEEEF10D0>:
Traceback (most recent call last):
  File "C:\Users\15072\anaconda3\envs\pychange\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 313, in _callback
    try:
KeyboardInterrupt: 


In [ ]:
# Pychange Timing
%timeit pelt_segment(ExponentialMeanVarCost().fit(p_test_series), min_len, max_cp, pen, 1)

In [ ]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Exponential").fit(p_test_series).predict()

## Gamma Mean+Var

In [ ]:
pelt_segment(GammaMeanVarCost().fit(g_test_series), min_len, max_cp, pen, 1)

In [ ]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Gamma").fit(g_test_series).predict()

In [ ]:
# Pychange Timing
%timeit pelt_segment(GammaMeanVarCost().fit(g_test_series), min_len, max_cp, pen, 1)

In [ ]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Gamma").fit(g_test_series).predict().predict()

## Nonparametric

In [ ]:
pelt_segment(NonParametricCost(k).fit(test_series), min_len, max_cp, pen, 1)

In [ ]:
ROfflineChangepoint('np', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, nquantiles=k).fit(test_series).predict()

In [ ]:
# Pychange Timing
%timeit pelt_segment(NonParametricCost(k).fit(test_series), min_len, max_cp, pen, 1)

In [ ]:
# R timing
%timeit ROfflineChangepoint('np', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, nquantiles=k).fit(test_series).predict()

# Binary Segmentation

## L1

In [ ]:
# L1 cost
binary_segment(L1Cost().fit(sm_test_series), min_len, pen)

In [ ]:
rpt.Binseg(model='l1', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

In [ ]:
%timeit binary_segment(L1Cost().fit(sm_test_series), min_len, pen)

In [ ]:
%timeit rpt.Binseg(model='l1', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

## L2

In [ ]:
# L2 cost
binary_segment(L2Cost().fit(sm_test_series), min_len, pen)

In [ ]:
rpt.Binseg(model='l2', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

In [ ]:
%timeit binary_segment(L2Cost().fit(sm_test_series), min_len, pen)

In [ ]:
%timeit rpt.Binseg(model='l2', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

## Normal Mean

In [ ]:
# Normal mean
binary_segment(NormalMeanCost().fit(test_series), min_len, pen)

In [ ]:
ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

In [ ]:
# Pychange Timing
%timeit binary_segment(NormalMeanCost().fit(test_series), min_len, pen)

In [ ]:
# R timing
%timeit ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

## Normal Var

In [ ]:
# Normal mean
binary_segment(NormalVarCost().fit(test_series), min_len, pen)

In [ ]:
ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

In [ ]:
# Pychange Timing
%timeit binary_segment(NormalVarCost().fit(test_series), min_len, pen)

In [ ]:
# R timing
%timeit ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

## Normal Mean+Var

In [ ]:
# Normal mean
binary_segment(NormalMeanVarCost().fit(test_series), min_len, pen)

In [ ]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

In [ ]:
# Pychange Timing
%timeit binary_segment(NormalMeanVarCost().fit(test_series), min_len, pen)

In [ ]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

## Poisson Mean+Var

In [ ]:
# Normal mean
binary_segment(PoissonMeanVarCost().fit(p_test_series), min_len, pen)

In [ ]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, test_stat='Poisson', Q=100).fit(p_test_series).predict()

In [ ]:
# Pychange Timing
%timeit binary_segment(PoissonMeanVarCost().fit(p_test_series), min_len, pen)

In [ ]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, test_stat='Poisson', Q=100).fit(p_test_series).predict()

# Bayesian Online Changepoint

In [4]:
OnlineCP(ConstantHazard(), StudentTProb(), 5, 0.5).update(sm_test_series).get_cps()

[98, 202, 399, 403, 409, 431, 439]

In [3]:
ROCP().fit(sm_test_series).predict()

array([101, 201, 301, 401], dtype=int64)

In [5]:
%timeit OnlineCP(ConstantHazard(), StudentTProb(), 5, 0.5).update(sm_test_series).get_cps()

19 ms ± 500 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit ROCP().fit(sm_test_series).predict()

255 ms ± 3.56 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
