In [1]:
# Importing packages
import numpy as np
from pychange.costs import L1Cost, L2Cost, NormalMeanCost, NormalVarCost, NormalMeanVarCost,NormalMeanVarCostFast, PoissonMeanVarCost, ExponentialMeanVarCost, GammaMeanVarCost, NonParametricCost, NonParametricCostParallel
from pychange.segment import amoc_segment, pelt_segment, binary_segment, amoc_segment_parallel, pelt_segment_parallel, binary_segment_parallel
from pychange.online import ConstantHazard, StudentTProb, OnlineCP, StudentTProbParallel, OnlineCPParallel
from pychange.r import ROfflineChangepoint, ROCP
import ruptures as rpt
%load_ext line_profiler

In [2]:
# Creating Normal synthetic data
size = 2000
sm_size = 2000
k = 20
min_len = 10
max_cp = 40
pen = 100.0
test_series = np.hstack([np.random.normal(0, 1, (size,)),
                         np.random.normal(6, 1, (size,)),
                         np.random.normal(0, 2, (size,)),
                         np.random.normal(-4, 1, (size,)),
                         np.random.normal(3, 1, (size,)),
                         ] * 8)

sm_test_series = np.hstack([np.random.normal(0, 1, (sm_size,)),
                         np.random.normal(6, 1, (sm_size,)),
                         np.random.normal(0, 2, (sm_size,)),
                         np.random.normal(-4, 1, (sm_size,)),
                         np.random.normal(3, 1, (sm_size,)),
                         ] * 2)

p_test_series = np.hstack([np.random.poisson(2, (size,)),
                         np.random.poisson(6, (size,)),
                         np.random.poisson(10, (size,)),
                         np.random.poisson(4, (size,)),
                         np.random.poisson(3, (size,)),
                         ] * 8)

g_test_series = p_test_series + 1

# AMOC

## Normal Mean

In [3]:
# Normal mean
amoc_segment(NormalMeanCost().fit(test_series), min_len, pen)

5001

In [4]:
# Normal mean
amoc_segment_parallel(NormalMeanCost().fit(test_series), min_len, pen)

5001

In [5]:
ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='AMOC', minseglen=min_len).fit(test_series).predict()

array([5001.])

In [6]:
# Pychange Timing
%timeit amoc_segment(NormalMeanCost().fit(test_series), min_len, pen)

1.57 ms ± 7.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [7]:
# R timing
%timeit ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Normal", minseglen=min_len).fit(test_series).predict()

8.23 ms ± 185 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
# Pychange Timing
%timeit amoc_segment_parallel(NormalMeanCost().fit(test_series), min_len, pen)

661 µs ± 14.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


## Normal Var

In [27]:
# Normal mean
amoc_segment(NormalVarCost().fit(test_series), min_len, pen)

10000

In [28]:
ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='AMOC', minseglen=min_len).fit(test_series).predict()

array([10000.])

In [29]:
# Pychange Timing
%timeit amoc_segment(NormalVarCost().fit(test_series), min_len, pen)

22.9 ms ± 132 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [30]:
# R timing
%timeit ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Normal", minseglen=min_len).fit(test_series).predict()

48.4 ms ± 1.55 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Normal Mean+Var

In [3]:
# Normal mean
amoc_segment(NormalMeanVarCost().fit(test_series), min_len, pen)

1560002

In [4]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', minseglen=min_len).fit(test_series).predict()

array([1560002.])

In [7]:
# Normal mean
amoc_segment_parallel(NormalMeanVarCostFast().fit(test_series), min_len, pen)

1560002

In [5]:
# Pychange Timing
%timeit amoc_segment(NormalMeanVarCost().fit(test_series), min_len, pen)

63.8 ms ± 553 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Normal", minseglen=min_len).fit(test_series).predict()

264 ms ± 19.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit amoc_segment_parallel(NormalMeanVarCostFast().fit(test_series), min_len, pen)

20.4 ms ± 71.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Poisson Mean+Var

In [35]:
# Normal mean
amoc_segment(PoissonMeanVarCost().fit(p_test_series), min_len, pen)

10000

In [36]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Poisson", minseglen=min_len).fit(p_test_series).predict()

array([10000.])

In [37]:
# Pychange Timing
%timeit amoc_segment(PoissonMeanVarCost().fit(p_test_series), min_len, pen)

12 ms ± 24.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [38]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Poisson", minseglen=min_len).fit(p_test_series).predict()

262 ms ± 6.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Exponential

In [3]:
amoc_segment(ExponentialMeanVarCost().fit(p_test_series), min_len, pen)

10000

In [4]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Exponential", minseglen=min_len).fit(p_test_series).predict()

array([10000.])

In [5]:
%timeit amoc_segment(ExponentialMeanVarCost().fit(p_test_series), min_len, pen)

11.5 ms ± 75.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Exponential", minseglen=min_len).fit(p_test_series).predict()

254 ms ± 6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Gamma

In [3]:
amoc_segment(GammaMeanVarCost().fit(g_test_series), min_len, pen)

10000

In [4]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Gamma", minseglen=min_len).fit(g_test_series).predict()

array([10000.])

In [5]:
%timeit amoc_segment(GammaMeanVarCost().fit(g_test_series), min_len, pen)

11.4 ms ± 44.7 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='AMOC', test_stat="Gamma", minseglen=min_len).fit(g_test_series).predict()

246 ms ± 8.35 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Nonparametric

In [17]:
# Normal mean
amoc_segment(NonParametricCost(k).fit(test_series), min_len, pen)

80000

In [18]:
# Pychange Timing
%timeit amoc_segment(NonParametricCost(k).fit(test_series), min_len, pen)

1.56 s ± 16 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [19]:
# Normal mean
amoc_segment_parallel(NonParametricCost(k).fit(test_series), min_len, pen)

80000

In [20]:
# Pychange Timing
%timeit amoc_segment_parallel(NonParametricCost(k).fit(test_series), min_len, pen)

680 ms ± 25.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [21]:
# Normal mean
amoc_segment(NonParametricCostParallel(k).fit(test_series), min_len, pen)

80000

In [22]:
# Pychange Timing
%timeit amoc_segment(NonParametricCostParallel(k).fit(test_series), min_len, pen)

1.18 s ± 46.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [23]:
# Normal mean
amoc_segment_parallel(NonParametricCostParallel(k).fit(test_series), min_len, pen)

80000

In [24]:
# Pychange Timing
%timeit amoc_segment_parallel(NonParametricCostParallel(k).fit(test_series), min_len, pen)

409 ms ± 28.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Pelt

## L1

In [41]:
# L1 cost
pelt_segment(L1Cost().fit(sm_test_series), min_len, max_cp, pen, 1)

array([100, 200, 300, 400], dtype=int64)

In [42]:
rpt.Pelt(model='l1', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

[100, 200, 300, 400, 500]

In [43]:
%timeit pelt_segment(L1Cost().fit(sm_test_series), min_len, max_cp, pen, 1)

37.5 ms ± 36.6 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [44]:
%timeit rpt.Pelt(model='l1', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

2.22 s ± 2.18 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## L2

In [45]:
# L1 cost
pelt_segment(L2Cost().fit(sm_test_series), min_len, max_cp, pen, 1)

array([100, 200, 300, 400], dtype=int64)

In [46]:
rpt.Pelt(model='l2', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

[100, 200, 300, 400, 500]

In [47]:
%timeit pelt_segment(L2Cost().fit(sm_test_series), min_len, max_cp, pen, 1)

1.8 ms ± 579 ns per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [48]:
%timeit rpt.Pelt(model='l2', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

700 ms ± 1.24 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Normal Mean

In [9]:
# Normal mean
pelt_segment(NormalMeanCost().fit(test_series), min_len, max_cp, pen, 1)

array([ 2500,  5001,  7500, 10000, 12500, 15000, 17501, 20000, 22500,
       25000, 27500, 30001, 32500, 35000, 37500, 40000, 42501, 45000,
       47500, 50000, 52500, 55001, 57500, 60000, 62500, 65000, 67501,
       70000, 72500, 75000, 77500, 80001, 82500, 85000, 87500, 90000,
       92501, 95000, 97500], dtype=int64)

In [10]:
# Normal mean
pelt_segment_parallel(NormalMeanCost().fit(test_series), min_len, max_cp, pen, 1)

array([ 2500,  5001,  7500, 10000, 12500, 15000, 17501, 20000, 22500,
       25000, 27500, 30001, 32500, 35000, 37500, 40000, 42501, 45000,
       47500, 50000, 52500, 55001, 57500, 60000, 62500, 65000, 67501,
       70000, 72500, 75000, 77500, 80001, 82500, 85000, 87500, 90000,
       92501, 95000, 97500], dtype=int64)

In [11]:
ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

array([ 2500,  5001,  7500, 10000, 12500, 15000, 17501, 20000, 22500,
       25000, 27500, 30001, 32500, 35000, 37500, 40000, 42501, 45000,
       47500, 50000, 52500, 55001, 57500, 60000, 62500, 65000, 67501,
       70000, 72500, 75000, 77500, 80001, 82500, 85000, 87500, 90000,
       92501, 95000, 97500], dtype=int32)

In [12]:
# Pychange Timing
%timeit pelt_segment(NormalMeanCost().fit(test_series), min_len, max_cp, pen, 1)

1.97 s ± 14.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [13]:
# R timing
%timeit ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

555 ms ± 790 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
# Normal mean
%timeit pelt_segment_parallel(NormalMeanCost().fit(test_series), min_len, max_cp, pen, 1)

1.93 s ± 26.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Normal Var

In [53]:
pelt_segment(NormalVarCost().fit(test_series), min_len, max_cp, pen, 1)

array([   671,    707,  10000,  20001,  29999,  40000,  50013,  50671,
        50707,  60000,  70001,  79999,  90000, 100013, 100671, 100707,
       110000, 120001, 129999, 140000, 150013, 150671, 150707, 160000,
       170001, 179999, 190000, 200013, 200671, 200707, 210000, 220001,
       229999, 240000, 250013, 250671, 250707, 260000, 270001, 279999,
       290000, 300013, 300671, 300707, 310000, 320001, 329999, 340000,
       350013, 350671, 350707, 360000, 370001, 379999, 390000],
      dtype=int64)

In [54]:
ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

array([ 10000,  20001,  29999,  40000,  50007,  60000,  70001,  79999,
        90000, 100007, 110000, 120001, 129999, 140000, 150007, 160000,
       170001, 179999, 190000, 200007, 210000, 220001, 229999, 240000,
       250007, 260000, 270001, 279999, 290000, 300007, 310000, 320001,
       329999, 340000, 350007, 360000, 370001, 379999, 390000],
      dtype=int32)

In [55]:
# Pychange Timing
%timeit pelt_segment(NormalVarCost().fit(test_series), min_len, max_cp, pen, 1)

49.5 s ± 427 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [56]:
# R timing
%timeit ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

1min 13s ± 166 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Normal Mean+Var

In [12]:
pelt_segment(NormalMeanVarCost().fit(test_series), min_len, max_cp, pen, 1)

array([ 2000,  4000,  6000,  8000, 10001, 12000, 14000, 16000, 18000,
       20001, 22000, 24000, 26000, 28000, 30001, 32000, 34000, 36000,
       38000, 40001, 42000, 44000, 46000, 48000, 50001, 52000, 54000,
       56000, 58000, 60001, 62000, 64000, 66000, 68000, 70001, 72000,
       74000, 76000, 78000], dtype=int64)

In [13]:
pelt_segment_parallel(NormalMeanVarCostFast().fit(test_series), min_len, max_cp, pen, 1)

array([ 2000,  4000,  6000,  8000, 10001, 12000, 14000, 16000, 18000,
       20001, 22000, 24000, 26000, 28000, 30001, 32000, 34000, 36000,
       38000, 40001, 42000, 44000, 46000, 48000, 50001, 52000, 54000,
       56000, 58000, 60001, 62000, 64000, 66000, 68000, 70001, 72000,
       74000, 76000, 78000], dtype=int64)

In [14]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

array([ 2000,  4000,  6000,  8000, 10001, 12000, 14000, 16000, 18000,
       20001, 22000, 24000, 26000, 28000, 30001, 32000, 34000, 36000,
       38000, 40001, 42000, 44000, 46000, 48000, 50001, 52000, 54000,
       56000, 58000, 60001, 62000, 64000, 66000, 68000, 70001, 72000,
       74000, 76000, 78000], dtype=int32)

In [15]:
# Pychange Timing
%timeit pelt_segment(NormalMeanVarCost().fit(test_series), min_len, max_cp, pen, 1)

1.73 s ± 35.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [16]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len).fit(test_series).predict()

4.35 s ± 42.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [17]:
# Pychange Timing
%timeit pelt_segment_parallel(NormalMeanVarCostFast().fit(test_series), min_len, max_cp, pen, 1)

1.75 s ± 14.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Poisson Mean+Var

In [61]:
pelt_segment(PoissonMeanVarCost().fit(p_test_series), min_len, max_cp, pen, 1)

array([ 10000,  19998,  30000,  39998,  50000,  60000,  69998,  80000,
        89998, 100000, 110000, 119998, 130000, 139998, 150000, 160000,
       169998, 180000, 189998, 200000, 210000, 219998, 230000, 239998,
       250000, 260000, 269998, 280000, 289998, 300000, 310000, 319998,
       330000, 339998, 350000, 360000, 369998, 380000, 389998],
      dtype=int64)

In [62]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Poisson").fit(p_test_series).predict()

array([ 10000,  19998,  30000,  39998,  50000,  60000,  69998,  80000,
        89998, 100000, 110000, 119998, 130000, 139998, 150000, 160000,
       169998, 180000, 189998, 200000, 210000, 219998, 230000, 239998,
       250000, 260000, 269998, 280000, 289998, 300000, 310000, 319998,
       330000, 339998, 350000, 360000, 369998, 380000, 389998],
      dtype=int32)

In [ ]:
# Pychange Timing
%timeit pelt_segment(PoissonMeanVarCost().fit(p_test_series), min_len, max_cp, pen, 1)

In [ ]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Poisson").fit(p_test_series).predict()

## Exponential Mean+Var

In [7]:
pelt_segment(ExponentialMeanVarCost().fit(p_test_series), min_len, max_cp, pen, 1)

array([ 10000,  19998,  30000,  39997,  50013,  60000,  69998,  80000,
        89997, 100013, 110000, 119998, 130000, 139997, 150013, 160000,
       169998, 180000, 189997, 200013, 210000, 219998, 230000, 239997,
       250013, 260000, 269998, 280000, 289997, 300013, 310000, 319998,
       330000, 339997, 350013, 360000, 369998, 380000, 389997],
      dtype=int64)

In [ ]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Exponential").fit(p_test_series).predict()

Exception ignored from cffi callback <function _callback at 0x0000013DEEEF10D0>:
Traceback (most recent call last):
  File "C:\Users\15072\anaconda3\envs\pychange\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 313, in _callback
    try:
KeyboardInterrupt: 


In [ ]:
# Pychange Timing
%timeit pelt_segment(ExponentialMeanVarCost().fit(p_test_series), min_len, max_cp, pen, 1)

In [ ]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Exponential").fit(p_test_series).predict()

## Gamma Mean+Var

In [ ]:
pelt_segment(GammaMeanVarCost().fit(g_test_series), min_len, max_cp, pen, 1)

In [ ]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Gamma").fit(g_test_series).predict()

In [ ]:
# Pychange Timing
%timeit pelt_segment(GammaMeanVarCost().fit(g_test_series), min_len, max_cp, pen, 1)

In [ ]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, test_stat="Gamma").fit(g_test_series).predict().predict()

## Nonparametric

In [11]:
pelt_segment(NonParametricCost(k).fit(test_series), min_len, max_cp, pen, 1)

array([ 1000,  2001,  3001,  4000,  5000,  6000,  7001,  8001,  9000,
       10000, 11000, 12001, 13001, 14000, 15000, 16000, 17001, 18001,
       19000, 20000, 21000, 22001, 23001, 24000, 25000, 26000, 27001,
       28001, 29000, 30000, 31000, 32001, 33001, 34000, 35000, 36000,
       37001, 38001, 39000], dtype=int64)

In [13]:
ROfflineChangepoint('np', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, nquantiles=k).fit(test_series).predict()

array([ 1000,  2001,  3001,  4000,  5000,  6000,  7001,  8001,  9000,
       10000, 11000, 12001, 13001, 14000, 15000, 16000, 17001, 18001,
       19000, 20000, 21000, 22001, 23001, 24000, 25000, 26000, 27001,
       28001, 29000, 30000, 31000, 32001, 33001, 34000, 35000, 36000,
       37001, 38001, 39000], dtype=int32)

In [12]:
# Pychange Timing
%timeit pelt_segment(NonParametricCost(k).fit(test_series), min_len, max_cp, pen, 1)

2.56 s ± 11.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [14]:
# R timing
%timeit ROfflineChangepoint('np', penalty='Manual', pen_value=pen, method='PELT', minseglen=min_len, nquantiles=k).fit(test_series).predict()

23.4 s ± 174 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
pelt_segment_parallel(NonParametricCostParallel(k).fit(test_series), min_len, max_cp, pen, 1)

array([ 1000,  2001,  3001,  4000,  5000,  6000,  7001,  8001,  9000,
       10000, 11000, 12001, 13001, 14000, 15000, 16000, 17001, 18001,
       19000, 20000, 21000, 22001, 23001, 24000, 25000, 26000, 27001,
       28001, 29000, 30000, 31000, 32001, 33001, 34000, 35000, 36000,
       37001, 38001, 39000], dtype=int64)

In [10]:
# Pychange Timing
%timeit pelt_segment_parallel(NonParametricCostParallel(k).fit(test_series), min_len, max_cp, pen, 1)

1.95 s ± 8.92 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# Binary Segmentation

## L1

In [ ]:
# L1 cost
binary_segment(L1Cost().fit(sm_test_series), min_len, pen)

In [ ]:
rpt.Binseg(model='l1', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

In [ ]:
%timeit binary_segment(L1Cost().fit(sm_test_series), min_len, pen)

In [ ]:
%timeit rpt.Binseg(model='l1', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

## L2

In [ ]:
# L2 cost
binary_segment(L2Cost().fit(sm_test_series), min_len, pen)

In [ ]:
rpt.Binseg(model='l2', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

In [ ]:
%timeit binary_segment(L2Cost().fit(sm_test_series), min_len, pen)

In [ ]:
%timeit rpt.Binseg(model='l2', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

## Normal Mean

In [3]:
# Normal mean
binary_segment(NormalMeanCost().fit(test_series), min_len, pen)

array([ 2000,  4002,  5999,  8000, 10000, 12000, 14002, 15999, 18000,
       20000, 22000, 24002, 25999, 28000, 30000, 32000, 34002, 35999,
       38000, 40000, 42000, 44002, 45999, 48000, 50000, 52000, 54002,
       55999, 58000, 60000, 62000, 64002, 65999, 68000, 70000, 72000,
       74002, 75999, 78000, 79999], dtype=int64)

In [4]:
# Normal mean
binary_segment_parallel(NormalMeanCost().fit(test_series), min_len, pen)

array([ 2000,  4002,  5999,  8000, 10000, 12000, 14002, 15999, 18000,
       20000, 22000, 24002, 25999, 28000, 30000, 32000, 34002, 35999,
       38000, 40000, 42000, 44002, 45999, 48000, 50000, 52000, 54002,
       55999, 58000, 60000, 62000, 64002, 65999, 68000, 70000, 72000,
       74002, 75999, 78000, 79999], dtype=int64)

In [5]:
ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

array([ 2000.,  4002.,  5999.,  8000., 10000., 12000., 14002., 15999.,
       18000., 20000., 22000., 24002., 25999., 28000., 30000., 32000.,
       34002., 35999., 38000., 40000., 42000., 44002., 45999., 48000.,
       50000., 52000., 54002., 55999., 58000., 60000., 62000., 64002.,
       65999., 68000., 70000., 72000., 74002., 75999., 78000.])

In [6]:
# Pychange Timing
%timeit binary_segment(NormalMeanCost().fit(test_series), min_len, pen)

19.1 ms ± 172 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
# R timing
%timeit ROfflineChangepoint('mean', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

55.4 ms ± 319 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit binary_segment_parallel(NormalMeanCost().fit(test_series), min_len, pen)

18.1 ms ± 71 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Normal Var

In [ ]:
# Normal mean
binary_segment(NormalVarCost().fit(test_series), min_len, pen)

In [ ]:
ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

In [ ]:
# Pychange Timing
%timeit binary_segment(NormalVarCost().fit(test_series), min_len, pen)

In [ ]:
# R timing
%timeit ROfflineChangepoint('var', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(test_series).predict()

## Normal Mean+Var

In [9]:
# Normal mean
binary_segment(NormalMeanVarCost().fit(sm_test_series), min_len, pen)

array([ 2000,  4000,  6000,  8000, 10000, 12000, 14000, 16000, 18000,
       19999], dtype=int64)

In [10]:
binary_segment_parallel(NormalMeanVarCostFast().fit(sm_test_series), min_len, pen)

array([ 2000,  4000,  6000,  8000, 10000, 12000, 14000, 16000, 18000,
       19999], dtype=int64)

In [11]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(sm_test_series).predict()

array([ 2000.,  4000.,  6000.,  8000., 10000., 12000., 14000., 16000.,
       18000.])

In [12]:
# Pychange Timing
%timeit binary_segment(NormalMeanVarCost().fit(sm_test_series), min_len, pen)

4.13 ms ± 10.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [13]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, Q=100).fit(sm_test_series).predict()

191 ms ± 498 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [14]:
%timeit binary_segment_parallel(NormalMeanVarCostFast().fit(sm_test_series), min_len, pen)

3.76 ms ± 5.53 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [15]:
%timeit rpt.Binseg(model='normal', min_size=min_len, jump=1).fit(sm_test_series).predict(pen=pen)

11.7 s ± 40.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Poisson Mean+Var

In [ ]:
# Normal mean
binary_segment(PoissonMeanVarCost().fit(p_test_series), min_len, pen)

In [ ]:
ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, test_stat='Poisson', Q=100).fit(p_test_series).predict()

In [ ]:
# Pychange Timing
%timeit binary_segment(PoissonMeanVarCost().fit(p_test_series), min_len, pen)

In [ ]:
# R timing
%timeit ROfflineChangepoint('meanvar', penalty='Manual', pen_value=pen, method='BinSeg', minseglen=min_len, test_stat='Poisson', Q=100).fit(p_test_series).predict()

# Bayesian Online Changepoint

In [3]:
OnlineCP(ConstantHazard(), StudentTProb(), 10, 0.99).update(sm_test_series).get_cps()

[1,
 17,
 21,
 55,
 57,
 130,
 139,
 201,
 307,
 313,
 315,
 317,
 319,
 322,
 332,
 336,
 401,
 427]

In [4]:
OnlineCPParallel(ConstantHazard(), StudentTProbParallel(), 10, 0.99).update(sm_test_series).get_cps()

[1,
 17,
 21,
 55,
 57,
 130,
 139,
 201,
 307,
 313,
 315,
 317,
 319,
 322,
 332,
 336,
 401,
 427]

In [5]:
ROCP().fit(sm_test_series).predict()

array([101, 201, 301, 302, 401], dtype=int64)

In [6]:
%timeit OnlineCP(ConstantHazard(), StudentTProb(), 5, 0.5).update(sm_test_series).get_cps()

18.4 ms ± 260 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [7]:
%timeit ROCP().fit(sm_test_series).predict()

252 ms ± 5.04 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [8]:
%timeit OnlineCPParallel(ConstantHazard(), StudentTProbParallel(), 5, 0.5).update(sm_test_series).get_cps()

17.6 ms ± 16 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
